devops:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "Dockerfile"

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "frontend/**"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/**"

machine-learning:
  - changed-files:
      - any-glob-to-any-file:
          - "ml/**"

feature-engineering:
  - changed-files:
      - any-glob-to-any-file:
          - "ml/notebooks/**"
          - "ml/utils.py"

data-engineering:
  - changed-files:
      - any-glob-to-any-file:
          - "ml/data/**"
          - "data/**"
          - "notebooks/**"
